export const MAP_CHANGE_BOUNDS = 'MAP_CHANGE_BOUNDS'
export const MAP_CHANGE_CENTER = 'MAP_CHANGE_CENTER'
export const MAP_CHANGE_ZOOM = 'MAP_CHANGE_ZOOM'
export const MAP_CLICK = 'MAP_CLICK'
export const MAP_CREATED = 'MAP_CREATED'

export const FILTER_UPDATE_PARAM = 'FILTER_UPDATE_PARAM'

export const REQUEST_MADE = 'REQUEST_MADE'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_ERROR = 'REQUEST_ERROR'

export const EVENT_ADD = 'EVENT_ADD'
export const EVENT_RESET = 'EVENT_RESET'
export const EVENT_REMOVE = 'EVENT_REMOVE'
export const EVENT_ACTIVATE = 'EVENT_ACTIVATE'
export const EVENT_DEACTIVATE = 'EVENT_DEACTIVATE'
export const EVENT_DEACTIVATE_ALL = 'EVENT_DEACTIVATE_ALL'
export const EVENT_HIGHLIGHT = 'EVENT_HIGHLIGHT'
export const EVENT_DEHIGHLIGHT = 'EVENT_DEHIGHLIGHT'

export const LAYOUT_CHANGE = 'LAYOUT_CHANGE'
